### ISSUE TITLE
Loot not splitting fairly at 2 people default investment.

### ISSUE THREAD

**Issue by NeoTheOne** [switchdv/nopixel-loot-splitter#1]
![image](https://user-images.githubusercontent.com/469830/121491529-528ba580-c9d6-11eb-8629-847eba39d729.png)
Seems kinda weird?
Is there a reason the first member would get more inked bags?
Why not just split in down the middle?

**Comment by NeoTheOne** [comment]
Hey man the project is looking good, made some issues so you can keep on making it great!

**Comment by switchdv** [comment]
Yes, I am aware of this issue. Currently working on splitting flexibility to trade payout around among members. The split currently prioritizes on giving inked bills over anything else starting from member 1 through member 4. Will update again soon.

**Comment by switchdv** [comment]
@NeoTheOne I just thought about this: using the same example, if it had been for a 3-person group instead of 2, the split of the inked bills would have caused the result to be "seemingly" unbalanced anyway, even for **default** investment, since in this case it would be 8 inked bills shared within 3 people.
I know this is annoying for evenly divisible payout, but the math used to split this would most likely stay the same. But I will still include a function to freely trade payout around among members, so you can adjust how many bags a member gets, etc. For example, you can trade 200 marked bills from member 1 for member 2's 1 inked bill.

**Comment by NeoTheOne** [comment]
@switchdv Yeah that's probably the best way to go about it honestly.
